### ISSUE TITLE
jsx container-kosmos fails on osx if <sandbox>/var/containers/ is opened once in Finder

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_core#297]
Finder creates a `.DS_Store` file with metadata of the folder.
https://github.com/threefoldtech/jumpscaleX_core/blob/4d8c13431c8cf9d6cc567ef51cc629273b13cd22/install/InstallTools.py#L4425 loops over all foldercontent  and assumes it are all containerfolders. When creating the DockerContainer instance, it tries to write a configfile inside the presumed folder, resulting in an error off course.
A workaround is to remove the .DS_Store file from the commandline or a fix can be to add `if os.path.isdir(os.path.join(cdir,name_found)):` to the above referenced code.

**Comment by xmonader** [comment]
solved in 8a462fdb1215575b080a6e6c7337ff2f0976b6d1

**Comment by Dina-Abd-Elrahman** [comment]
- blocked on this issue https://github.com/threefoldtech/jumpscaleX_core/issues/430

**Comment by xmonader** [comment]
I won't have this blocked on catalina installation. closing.

**Comment by robvanmieghem** [comment]
The commit does not fix the issue since it checks if `{DIR_BASE}/var/containers` is a directory, not the entry found inside this directory

**Comment by xmonader** [comment]
Now that i merged ur PR @robvanmieghem it should be fixed :)
